name: publish nodejs package

on:
    workflow_dispatch:

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Download workflow artifact
              uses: dawidd6/action-download-artifact@v7
              with:
                  workflow: build.yml
                  branch: main
                  name: MAA-nodejs-package
                  path: assets

            - uses: JS-DevTools/npm-publish@v3
              id: nodejs
              with:
                  package: assets/MAA-nodejs-package/maa-node
                  access: public
                  token: ${{ secrets.NPM_TOKEN }}

            - uses: JS-DevTools/npm-publish@v3
              with:
                  package: assets/MAA-nodejs-package/maa-node-win32-x64
                  access: public
                  token: ${{ secrets.NPM_TOKEN }}

            - uses: JS-DevTools/npm-publish@v3
              with:
                  package: assets/MAA-nodejs-package/maa-node-win32-arm64
                  access: public
                  token: ${{ secrets.NPM_TOKEN }}

            - uses: JS-DevTools/npm-publish@v3
              with:
                  package: assets/MAA-nodejs-package/maa-node-linux-x64
                  access: public
                  token: ${{ secrets.NPM_TOKEN }}

            - uses: JS-DevTools/npm-publish@v3
              with:
                  package: assets/MAA-nodejs-package/maa-node-linux-arm64
                  access: public
                  token: ${{ secrets.NPM_TOKEN }}

            - uses: JS-DevTools/npm-publish@v3
              with:
                  package: assets/MAA-nodejs-package/maa-node-darwin-x64
                  access: public
                  token: ${{ secrets.NPM_TOKEN }}

            - uses: JS-DevTools/npm-publish@v3
              with:
                  package: assets/MAA-nodejs-package/maa-node-darwin-arm64
                  access: public
                  token: ${{ secrets.NPM_TOKEN }}
